server:
  port: 8003
mybatis:
  type-aliases-package: com.wjl.springcloud.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db03?userUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: org.gjt.mm.mysql.Driver
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: springcloud-provider-dept-8003 #修改默认描述信息

info:
  app.name: wjl-springcloud
  company.name: com.wjl